<a href="https://colab.research.google.com/github/gdnsjf/educational-work/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [ ]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Как узнать объем памяти любого массива (★☆☆)

In [ ]:
a.nbytes

80

#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [ ]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [ ]:
a = np.arange(10, 50)
a = a [:: - 1 ]
a


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [ ]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [ ]:
a = np.nonzero([1, 2, 0, 0, 4, 0])
a

(array([0, 1, 4]),)

#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [ ]:
a = np.random.rand(3, 3, 3)
a

array([[[0.0693234 , 0.50111413, 0.96767893],
        [0.24202093, 0.42180022, 0.29876943],
        [0.14839926, 0.70122713, 0.22713737]],

       [[0.44583903, 0.96463886, 0.68539763],
        [0.05632331, 0.9532382 , 0.24726226],
        [0.200233  , 0.08686582, 0.83901712]],

       [[0.54969273, 0.2863385 , 0.41184258],
        [0.29518774, 0.13325266, 0.13442813],
        [0.35428494, 0.17612903, 0.34988422]]])

#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [ ]:
a = np.random.rand(10, 10)
a, a.min(), a.max()

(array([[0.44356647, 0.04978938, 0.73218712, 0.46819387, 0.52720483,
         0.92114802, 0.421254  , 0.62509067, 0.49482487, 0.90573066],
        [0.18527628, 0.4087148 , 0.82411262, 0.29373582, 0.04267016,
         0.07892575, 0.18696035, 0.78142761, 0.7060634 , 0.76201572],
        [0.7945148 , 0.38577898, 0.18118758, 0.85098838, 0.69790037,
         0.78549524, 0.87812869, 0.11763611, 0.15086281, 0.92534661],
        [0.81862665, 0.70464283, 0.45041081, 0.17677884, 0.50304565,
         0.62810899, 0.49941153, 0.87702887, 0.6022777 , 0.28164951],
        [0.20011015, 0.3880459 , 0.89980528, 0.58083097, 0.04567486,
         0.13188241, 0.23705355, 0.49832067, 0.6633612 , 0.16723831],
        [0.09657308, 0.92396596, 0.21230508, 0.34080755, 0.26604908,
         0.34690986, 0.39910724, 0.65200649, 0.61220984, 0.27588132],
        [0.32943889, 0.22534888, 0.57022352, 0.10836245, 0.78921819,
         0.6335219 , 0.27913404, 0.34379525, 0.91544871, 0.60929318],
        [0.41518618, 0.9674

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [ ]:
a = np.random.rand(30)
a, a.mean()

(array([0.83067503, 0.26362541, 0.89076606, 0.16424368, 0.54146835,
        0.31337061, 0.76546695, 0.95010954, 0.53698724, 0.75017211,
        0.32663843, 0.30054945, 0.08132841, 0.51388672, 0.43234797,
        0.05990923, 0.137007  , 0.90696156, 0.45972746, 0.78132864,
        0.93780456, 0.72518021, 0.35773678, 0.39287669, 0.58572785,
        0.61544453, 0.71751971, 0.62962417, 0.76239198, 0.35598795]),
 0.5362288087237675)

#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [ ]:
a = np.ones((3, 3))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [ ]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [ ]:
a = np.ones((5, 3))
b = np.ones((3, 2))
c = np.dot(a, b)
c

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [ ]:
a = np.arange(1,10)
a[2], a[7] = a[7], a[2]
a

array([1, 2, 8, 4, 5, 6, 7, 3, 9])

#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-9-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-9-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-9-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [ ]:
a = np.random.randint(1, 10, 10)
print(a)
b = np.random.randint(1, 10, 10)
print(b)
print(np.intersect1d(a, b))

[8 9 7 1 5 2 7 1 2 5]
[9 4 4 4 3 3 9 9 5 3]
[5 9]


#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [ ]:
a = np.ones(3) * 2
print(a)
b = np.ones(3) * 2
print(b)
np.add(a, b, b)
np.divide(a, 2, a)
np.negative(a, a)
np.multiply(a, b, a)

[2. 2. 2.]
[2. 2. 2.]


array([-4., -4., -4.])

#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [ ]:
a = np.zeros((5, 5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [ ]:
a = np.linspace(0, 1, 11, endpoint=False) [1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [ ]:
a = np.random.randint(1, 100, 10)
a.sort()
a

array([ 4,  7, 15, 38, 41, 48, 49, 54, 76, 98])

#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [ ]:
a = np.arange(10)
%time np.add.reduce(a)
%time np.sum(a)

CPU times: user 59 µs, sys: 6 µs, total: 65 µs
Wall time: 68.9 µs
CPU times: user 78 µs, sys: 4 µs, total: 82 µs
Wall time: 96.8 µs


45

#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [ ]:
a = np.random.randint(1, 10, 10)
print(a)
b = np.random.randint(1, 10, 10)
print(b)
c = np.allclose(a, b)
c

[2 3 4 1 5 2 4 6 5 8]
[5 1 3 3 2 6 6 7 2 1]


False

#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [ ]:
a = np.random.randint(1, 100, 10)
print(a)
a[a.argmax()] = 0
a

[76  4 43 27 61 36 90 70 25 40]


array([76,  4, 43, 27, 61, 36,  0, 70, 25, 40])

#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(dtype.__name__, np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(dtype.__name__, np.finfo(dtype).min, np.finfo(dtype).max)

int8 -128 127
int32 -2147483648 2147483647
int64 -9223372036854775808 9223372036854775807
float32 -3.4028235e+38 3.4028235e+38
float64 -1.7976931348623157e+308 1.7976931348623157e+308


#### 26. Как вывести все значения большого массива? (★★☆)

In [ ]:
np.set_printoptions(threshold = float("inf"))
a = np.ones((30, 40))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [ ]:
import scipy.spatial
a = np.zeros((100, 2))
a[:, 0] = np.arange(100) * 3
a[:, 1] = np.arange(100) * 4
print(a)
b = scipy.spatial.distance.cdist(a, a)
print('\n', b)

[[  0.   0.]
 [  3.   4.]
 [  6.   8.]
 [  9.  12.]
 [ 12.  16.]
 [ 15.  20.]
 [ 18.  24.]
 [ 21.  28.]
 [ 24.  32.]
 [ 27.  36.]
 [ 30.  40.]
 [ 33.  44.]
 [ 36.  48.]
 [ 39.  52.]
 [ 42.  56.]
 [ 45.  60.]
 [ 48.  64.]
 [ 51.  68.]
 [ 54.  72.]
 [ 57.  76.]
 [ 60.  80.]
 [ 63.  84.]
 [ 66.  88.]
 [ 69.  92.]
 [ 72.  96.]
 [ 75. 100.]
 [ 78. 104.]
 [ 81. 108.]
 [ 84. 112.]
 [ 87. 116.]
 [ 90. 120.]
 [ 93. 124.]
 [ 96. 128.]
 [ 99. 132.]
 [102. 136.]
 [105. 140.]
 [108. 144.]
 [111. 148.]
 [114. 152.]
 [117. 156.]
 [120. 160.]
 [123. 164.]
 [126. 168.]
 [129. 172.]
 [132. 176.]
 [135. 180.]
 [138. 184.]
 [141. 188.]
 [144. 192.]
 [147. 196.]
 [150. 200.]
 [153. 204.]
 [156. 208.]
 [159. 212.]
 [162. 216.]
 [165. 220.]
 [168. 224.]
 [171. 228.]
 [174. 232.]
 [177. 236.]
 [180. 240.]
 [183. 244.]
 [186. 248.]
 [189. 252.]
 [192. 256.]
 [195. 260.]
 [198. 264.]
 [201. 268.]
 [204. 272.]
 [207. 276.]
 [210. 280.]
 [213. 284.]
 [216. 288.]
 [219. 292.]
 [222. 296.]
 [225. 300.]
 [228. 304.]

#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [ ]:
a = (np.random.rand(5)*100).astype(np.float32)
print(a)
b = a.view(np.int32)
b[:] = a
print(b)

[56.76905  66.1021   16.879765 27.9474   90.729416]
[56 66 16 27 90]


#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
a = np.genfromtxt(s, delimiter=",", dtype=np.int8)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [ ]:
a = np.random.rand(5, 2)
print(a)
b = a - a.mean(axis=1, keepdims=True)
print('\n', b)

[[0.84652054 0.39661149]
 [0.0231171  0.70359202]
 [0.30743013 0.21125422]
 [0.24992115 0.87553778]
 [0.82709565 0.67934582]]

 [[ 0.22495453 -0.22495453]
 [-0.34023746  0.34023746]
 [ 0.04808795 -0.04808795]
 [-0.31280832  0.31280832]
 [ 0.07387492 -0.07387492]]


#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [ ]:
a = np.ones(10)
print(a)
b = np.random.randint(0,len(a),20)
print(b)
a += np.bincount(b, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 1 1 2 2 3 1 7 6 5 4 8 6 9 3 1 2 0 9 2]
[2. 5. 5. 4. 2. 2. 3. 2. 2. 3.]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [ ]:
a = [15,2,23,4,9,6]
print(a)
i = [1,3,1,5,6,8]
print(i)
c = np.bincount(i,a)
print(c)

[15, 2, 23, 4, 9, 6]
[1, 3, 1, 5, 6, 8]
[ 0. 38.  0.  2.  0.  4.  9.  0.  6.]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [ ]:
a = np.random.randint(0,2,(3,4,3,4))
print(a)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print('\n', sum)

[[[[1 0 1 0]
   [1 0 1 0]
   [0 1 0 0]]

  [[1 0 0 0]
   [0 1 0 0]
   [1 0 1 0]]

  [[1 1 1 0]
   [1 0 0 0]
   [0 0 0 0]]

  [[0 0 1 1]
   [1 0 0 1]
   [1 0 0 0]]]


 [[[0 0 1 1]
   [1 0 1 1]
   [0 1 1 0]]

  [[1 0 1 0]
   [1 0 0 1]
   [0 0 1 1]]

  [[1 1 1 1]
   [1 0 0 1]
   [0 0 0 0]]

  [[0 1 1 0]
   [1 0 0 1]
   [1 0 0 0]]]


 [[[1 0 1 1]
   [1 0 1 0]
   [1 1 1 0]]

  [[0 0 1 0]
   [1 1 0 1]
   [0 1 1 1]]

  [[1 1 1 0]
   [1 0 1 1]
   [1 0 0 1]]

  [[1 1 0 0]
   [0 1 1 1]
   [0 0 0 0]]]]

 [[5 4 4 5]
 [7 6 6 5]
 [8 7 8 5]]


#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.zeros(len(a) + (len(a)-1)*(3))
b[::3+1] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [ ]:
a = np.ones((5,5,3))
print(a)
b = 2*np.ones((5,5))
print('\n',b)
print(f'\n a*b = \n',a * b[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

 a*b = 
 [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view
a = np.arange(20)
print(a)
print(sliding_window_view(a, window_shape=3).mean(axis=-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [ ]:
a = np.arange(10)
print(a)
print(sliding_window_view(a, window_shape=3))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [ ]:
P0 = np.random.randint(0,10,(5,2))
P1 = np.random.randint(0,10,(5,2))
p =  np.random.randint(0, 10, (5,2))
print('Координаты точки: \n', p)
print(f'Расстояния:\n',np.array([distance(P0,P1,p_i) for p_i in p]))

Координаты точки: 
 [[3 1]
 [0 9]
 [4 1]
 [4 8]
 [4 2]]
Расстояния:
 [[3.85695556 6.26099034 2.42535625 2.6        0.32539569]
 [0.84664878 0.4472136  6.06339063 0.2        8.78568354]
 [3.10437887 5.81377674 2.66789188 1.8        0.10846523]
 [1.50515339 0.4472136  4.12310563 2.4        6.94177465]
 [2.44587426 4.91934955 1.69774938 1.2        1.08465229]]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
a = np.arange(1,15,dtype=np.uint32)
b = stride_tricks.as_strided(a,(11,4),(4,4))
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [ ]:
N = 10
a = np.random.randint(2,size=(N,N))
print(a)
rank = np.linalg.matrix_rank(a)
print(f'Ранг =', rank)

[[1 1 0 0 0 1 1 1 0 0]
 [0 0 1 1 0 1 0 1 0 1]
 [1 1 0 0 0 0 1 1 0 0]
 [1 0 0 1 0 0 0 0 0 1]
 [1 1 0 0 0 1 1 1 1 1]
 [1 0 1 0 0 0 0 1 1 0]
 [0 1 1 0 1 0 0 0 0 1]
 [1 0 0 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 0 1]]
Ранг = 10


#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [ ]:
a = np.random.randint(0,20,30)
print(a)
print(np.bincount(a).argmax())

[ 8 11  5  3  0 18 13  6  2  2  1  1 13  1  4 10  4  2  0  1 19 13  1  0
 10  9  8  1  7 16]
1


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
print('A:\n', A)
B = np.random.randint(0,5,(2,2))
print('В:\n', B)
C = (A[..., np.newaxis, np.newaxis] == B)
index_rows = np.where(C.any((3,1)).all(1))[0]
print('Cтроки:', index_rows)

A:
 [[0 1 0]
 [3 1 0]
 [2 3 1]
 [3 3 2]
 [1 1 4]
 [3 2 3]
 [4 2 4]
 [3 4 2]]
В:
 [[2 3]
 [1 1]]
Cтроки: [1 2]


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [ ]:
a = np. array([ [ 6, 4, 9, 6, 2, 9 ], [ 3, 7, 7, 6, 1, 3 ] ])
print(a)
b, index_array = np. unique(a, return_index = True)
print("\n",b)

[[6 4 9 6 2 9]
 [3 7 7 6 1 3]]

 [1 2 3 4 6 7 9]
